# Generated by Django 4.1 on 2022-08-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "codigo_do_produto",
                    models.IntegerField(
                        max_length=100, verbose_name="Codigo de produto"
                    ),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=9, verbose_name="Preço"
                    ),
                ),
                (
                    "estoque",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=5,
                        verbose_name="Quantidade em Estoque",
                    ),
                ),
            ],
        ),
    ]
