# Generated by Django 4.1 on 2022-09-02 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_product_created_at_product_updated_at"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product",
            new_name="Produto",
        ),
    ]
